name: Retinbox Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.8.x

      - name: Deploy to Retinbox
        run: npm run deploy
        env:
          RTH_API_KEY: ${{ secrets.RTH_API_KEY }}
